id: A541059F3
title: Prayer for the Long Life of His Holiness the Dalai Lama
type: translation
pechas:
- IFA5AAB1C
- IA035F54A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:25.038074
  last_modified_at: 2023-01-04 11:53:25.038085
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IFA5AAB1C/8AC9: 41B6
  IA035F54A/45CA: 41B6
